- config/routes.rb
Reverts lkkrzize/global_connect#1
> Revert "edit page route"

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/pages_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/event.rb
- app/views/pages/home.html.erb
- app/views/shared/_app_map.html.erb
- config/importmap.rb
- config/initializers/geocoder.rb
- db/migrate/20250529134505_add_coordinates_to_events.rb
- db/schema.rb
Added the map with markers and removed the 3D image holder
> added map to landing page with markers

- app/assets/stylesheets/pages/_home.scss
- db/schema.rb
Added css to center the text and map
> Centering text and map

- app/javascript/controllers/map_controller.js
- app/views/pages/home.html.erb
Moved the javascript from home html file to map controller js
> moved js from home to js file

- app/controllers/events_controller.rb
code added by error causing the web to break, removed the code now
> fixed error in events controller

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
> Centered map on event location

- app/assets/stylesheets/pages/_home.scss
> added opacity to the background img in the landing page

- app/controllers/events_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/events/show.html.erb
- app/views/layouts/application.html.erb
Added an icon to the register button and also added a button for user to join chat at a later stage
> Added join the chat btn on the event page

- db/seeds.rb
Added new data to the seed file
> Seed file added more events, guests

- app/controllers/events_controller.rb
- app/javascript/controllers/map_controller.js
The landing page user location btn works and shows events only where the user is located
> map user search location fixed

- app/assets/stylesheets/components/_card.scss
- app/views/events/index.html.erb
> overlay card becomes red when the event is in the past

- app/views/events/show.html.erb
I added a div around user reviews, moved the user that leaves review to the right corner and styled it
> reviews box styled

- db/seeds.rb
Added messages to populate chats and also event attendees
> edit seed file to populate messages and event attendees

- app/views/events/show.html.erb
> registration btn disabled for past events

- app/assets/stylesheets/pages/show.scss
- app/controllers/events_controller.rb
- app/javascript/application.js
- app/views/events/show.html.erb
- app/views/layouts/application.html.erb
> delete and edit btn icons

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
added styling to the buttons on landing page
> landing page buttons styled

- app/assets/stylesheets/components/_card.scss
- app/models/user.rb
- app/views/events/index.html.erb
Added event logic for the user to have a badge on the events that they're hosting
> Added a badge to highlight events hosted by user

- app/views/events/chat.html.erb
> avatars added to the attendees

- app/controllers/profiles_controller.rb
- app/models/user.rb
- app/views/events/index.html.erb
- app/views/profiles/show.html.erb
**brought back the carousel**
**while keeping the list**
> added back carousel while also having option to see list

- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/_form.html.erb
edit/new form should function as expected now
> edit-new form now uses correct data

- app/assets/stylesheets/components/_chat.scss
- app/views/events/show.html.erb
> showing who organised event in show page
